Chore: replace testnet rpc url
godwokenrises/light-godwoken pull request #233
Opened 2022-11-16 12:11 UTC by ShookLyngs

Godwoken has a new Testnet RPC url, replacing it.

2022-11-16 16:10 UTC, Flouse approved these changes

2022-11-16 17:09 UTC, Flouse requested changes

2022-11-16 17:09 UTC, Flouse commented on packages/light-godwoken/src/config/predefined/testnet.ts
>      SCANNER_URL: "https://v1.betanet.gwscan.com/",
```suggestion
    SCANNER_URL: "https://v1.testnet.gwscan.com/",
```

2022-11-16 17:11 UTC, Flouse requested changes

2022-11-16 17:11 UTC, Flouse commented on packages/light-godwoken/src/config/predefined/testnet.ts
>      SCANNER_API: "https://api.v1.betanet.gwscan.com/api/",
```suggestion
    SCANNER_URL: "https://v1.testnet.gwscan.com/",
    SCANNER_API: "https://api.v1.testnet.gwscan.com/api/",
```

2022-11-17 01:43 UTC, ShookLyngs commented on packages/light-godwoken/src/config/predefined/testnet.ts
>      SCANNER_API: "https://api.v1.betanet.gwscan.com/api/",
GwScan haven't provide a `api.v1.testnet.gwscan.com/api` api yet, so we still need to use this one for now.

2022-11-17 15:17 UTC, Flouse approved these changes

2022-11-17 15:18 UTC, merged