feat: Network switching strategy adjustment
godwokenrises/light-godwoken pull request #260
Opened 2023-02-08 12:08 UTC by GitOfJason

This pull request implements this feature

#254

2023-02-08 16:33 UTC, Flouse commented
test link: https://godwoken-bridge-mainnet-7jeqgbmsp-godwoken.vercel.app

Please check the following test cases:
- [ ] switch from Godwoken mainnet_v0 to mainnet_v1 
- [ ] switch from Godwoken mainnet_v1 to mainnet_v0

cc @Dawn-githup

2023-02-08 17:02 UTC, ShookLyngs requested changes

2023-02-08 17:18 UTC, Dawn-githup commented
Click the blank area outside the pop-up box to prompt that the pop-up box will also disappear 

Misclick may occur. I think it should not disappear unless the user closes it or clicks cancel confirm

2023-02-08 17:26 UTC, GitOfJason commented on apps/godwoken-bridge/src/views/GodwokenBridge.tsx
> +      <NetworkMismatchModal
That's a good idea

2023-02-08 17:32 UTC, Dawn-githup commented
> test link: https://godwoken-bridge-mainnet-7jeqgbmsp-godwoken.vercel.app
> 
> Please check the following test cases:
> 
> * [ ]  switch from Godwoken mainnet_v0 to mainnet_v1
> * [ ]  switch from Godwoken mainnet_v1 to mainnet_v0
> 
> cc @Dawn-githup
> 
> ## Reference
> Godwoken Public Networks - https://docs.godwoken.io/connectionInfo

regression test case
- [ ] switch from Godwoken mainnet to testnet
- [ ] switch from Godwoken testnet to mainnet
- [ ] switch from Godwoken mainnet&testnet to ethernet& Other networks
- [ ] Compatible display of the pop-up box on the mobile terminal

2023-02-08 17:43 UTC, GitOfJason commented
> Click the blank area outside the pop-up box to prompt that the pop-up box will also disappear
> 
> Misclick may occur. I think it should not disappear unless the user closes it or clicks cancel confirm

Fixed

2023-02-08 18:01 UTC, Dawn-githup commented
> > Click the blank area outside the pop-up box to prompt that the pop-up box will also disappear
> > Misclick may occur. I think it should not disappear unless the user closes it or clicks cancel confirm
> 
> Fixed

Thanks @GitOfJason

2023-02-08 18:03 UTC, Dawn-githup approved these changes

2023-02-08 19:38 UTC, ShookLyngs approved these changes

2023-02-09 03:31 UTC, merged

2023-02-09 09:08 UTC, Flouse commented
When I visited https://godwoken-bridge-mainnet-qkjgqqcvp-godwoken.vercel.app/#/v0 , and switch between mainnet_v1 and mainnet_v0, it showed

![image](https://user-images.githubusercontent.com/1297478/217766471-c75c8dfb-df8f-4c5c-84e6-742e7aa9ce62.png)

@ShookLyngs @Dawn-githup could you confirm this issue?

2023-02-09 09:13 UTC, GitOfJason commented
> 

@Flouse I know what the problem is and I will fix it

2023-02-09 09:52 UTC, GitOfJason commented
> @Flouse The network switching part only detects if the network from the provider changes, and our app does not actually need to add mainnet/testnet v0 networks to the provider. Which means users add v1 networks to their providers even if they're using the v0 bridge. However, it does look weird.
> 
> @GitOfJason How do you plan to fix it?

Sorry, I understand it wrong.  As @ShookLyngs  said, in order to make the network name look less strange, we should specify a display name instead of using layer2Config. CHAIN_ NAME as the displayed name

2023-02-09 09:59 UTC, ShookLyngs commented
> Sorry, I understand it wrong. As @ShookLyngs said, in order to make the network name look less strange, we should specify a display name instead of using `layer2Config. CHAIN_ NAME` as the displayed name

It seems your first attemp was friendly enough, how about using the `isMainnet` value:
```typescript
const networkName = `Godwoken ${isMainnet ? "Mainnet" : "Testnet"}`;
```

2023-02-09 10:06 UTC, GitOfJason commented
> > Sorry, I understand it wrong. As @ShookLyngs said, in order to make the network name look less strange, we should specify a display name instead of using `layer2Config. CHAIN_ NAME` as the displayed name
> 
> It seems your first attemp was friendly enough, how about using the predefined `isMainnet` variable:
> 
> ```ts
> const networkName = `Godwoken ${isMainnet ? "Mainnet" : "Testnet"}`;
> ```

@Flouse @ShookLyngs  I will fix it in this way