Fix the status of a long time l2Pending withdrawal
godwokenrises/light-godwoken pull request #300
Opened 2023-04-20 04:37 UTC by Flouse

If a withdrawal stays in l2Pending too long,
then it may have failed for some reason,
such as `over-withdraw`.

2023-04-20 04:46 UTC, ShookLyngs requested changes

2023-04-20 04:46 UTC, ShookLyngs commented on apps/godwoken-bridge/src/components/Withdrawal/ListV1.tsx
> +            const elapsedMins = (Date.now() - new Date(withdrawalTx.date)) / 1000 / 60;
```suggestion
            const elapsedMins = (Date.now() - new Date(withdrawalTx.date).getTime()) / 1000 / 60;
```

2023-04-27 08:03 UTC, classicalliu approved these changes

2023-04-27 08:05 UTC, ShookLyngs approved these changes

2023-04-27 08:48 UTC, Flouse commented on apps/godwoken-bridge/src/components/Withdrawal/WithdrawalItemV1.tsx
> +  now?: number; // TODO: `now` is not used, remove it?
```suggestion
```

2023-04-27 13:31 UTC, Dawn-githup approved these changes

2023-04-27 14:48 UTC, merged